# Generated by Django 3.2 on 2022-10-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='姓名')),
            ],
        ),
        migrations.AlterField(
            model_name='receive',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='emergency_degree',
            field=models.SmallIntegerField(choices=[(1, 'Urgency'), (2, 'Norm'), (3, 'Looseness')], default=3, verbose_name='紧急程度'),
        ),
    ]
