# Generated by Django 3.2 on 2022-10-08 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_auto_20221008_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='user_id',
            new_name='user',
        ),
    ]
