# Generated by Django 3.2 on 2022-10-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_auto_20221009_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='material_type',
            field=models.CharField(choices=[('医疗物资', 'Medicalsupplies'), ('食物', 'Foods'), ('d', '生活必须品'), ('其他', 'Others')], default='d', max_length=8, verbose_name='物品种类'),
        ),
    ]
