# Generated by Django 3.2 on 2022-10-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_alter_requirement_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='material_type',
            field=models.CharField(choices=[('医疗物资', 'Medicalsupplies'), ('食物', 'Foods'), ('生活用品', 'Dailynecessities'), ('其他', 'Others')], default='d', max_length=8, verbose_name='物品种类'),
        ),
    ]
