# Generated by Django 3.2 on 2022-10-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_rename_houser_numbser_user_house_numbser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='house_numbser',
            new_name='house_number',
        ),
    ]
