# Generated by Django 3.2 on 2022-10-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_rename_house_numbser_user_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
    ]
